# Generated by Django 3.1.4 on 2020-12-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201224_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Votre adresse'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Specialist_doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Specialite'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Votre numeros de telephone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heur de travail'),
        ),
    ]
