# Generated by Django 3.1.4 on 2020-12-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201225_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
